module org.application.gameshelfapp {
    requires javafx.controls;
    requires javafx.fxml;
    requires google.api.client;
    requires com.google.api.client.extensions.java6.auth;
    requires com.google.api.client.extensions.jetty.auth;
    requires com.google.api.client.auth;
    requires com.google.api.client;
    requires com.google.api.client.json.gson;
    requires com.google.api.services.gmail;
    requires mail;
    requires org.apache.commons.codec;
    requires com.opencsv;
    requires jdk.httpserver;
    requires java.sql;
    requires com.google.gson;

    opens org.application.gameshelfapp to javafx.fxml;
    opens org.application.gameshelfapp.login.graphiccontrollers to javafx.fxml;
    opens org.application.gameshelfapp.buyvideogames.graphiccontrollers to javafx.fxml;
    exports org.application.gameshelfapp;
    exports org.application.gameshelfapp.login.graphiccontrollers;
    exports org.application.gameshelfapp.login.exception;
    exports org.application.gameshelfapp.login.boundary;
    exports org.application.gameshelfapp.login.bean;
    exports org.application.gameshelfapp.buyvideogames.boundary;
    exports org.application.gameshelfapp.buyvideogames.bean;
    exports org.application.gameshelfapp.buyvideogames.exception;
    exports org.application.gameshelfapp.buyvideogames.entities;
    exports org.application.gameshelfapp.buyvideogames.controller;
    exports org.application.gameshelfapp.login.controller;
    exports org.application.gameshelfapp.login.entities;
    exports org.application.gameshelfapp.buyvideogames.graphiccontrollers;
    opens org.application.gameshelfapp.buyvideogames.bean to com.google.gson;
    opens org.application.gameshelfapp.buyvideogames.entities to com.google.gson;
    exports org.application.gameshelfapp.sellvideogames.exception;
    exports org.application.gameshelfapp.registration.bean;
    exports org.application.gameshelfapp.registration.entities;
    exports org.application.gameshelfapp.registration.grapichcontroller;
    opens org.application.gameshelfapp.registration.grapichcontroller to javafx.fxml;
    exports org.application.gameshelfapp.registration.boundary;
    exports org.application.gameshelfapp.sellvideogames.bean;
    exports org.application.gameshelfapp.confirmsale.bean;
    opens org.application.gameshelfapp.confirmsale.bean to com.google.gson;
    exports org.application.gameshelfapp.confirmsale.boundary;
    exports org.application.gameshelfapp.confirmsale.entities;
    opens org.application.gameshelfapp.confirmsale.entities to com.google.gson;
    exports org.application.gameshelfapp.confirmsale.exceptions;
    exports org.application.gameshelfapp.confirmsale.graphiccontrollers;
    opens org.application.gameshelfapp.confirmsale.graphiccontrollers to javafx.fxml;
    exports org.application.gameshelfapp.sellvideogames.entities;
    opens org.application.gameshelfapp.sellvideogames.graphiccontrollers to javafx.fxml;
}